# Documentation: https://github.com/marketplace/actions/regex-issue-labeler
name: Label issues

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/issue_labeler_config.yml
          enable-versioned-regex: 0
          repo-token: ${{ secrets.ACCESS_TOKEN }}
