name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    uses: ./.github/workflows/new_issues_label.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
