name: Get package name

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  get_package_name:
    uses: martynov-alex/github_actions_examples/.github/workflows/get_package_name.yml@main

  print_package_name:
    runs-on: ubuntu-latest
    needs: get_package_name
    steps:
      - name: Print package name
        run: |
          echo ${{ needs.get_package_name.outputs.package_name }}