name: Create Pyrus task from pull request

on:
  pull_request:
    types:
      - reopened
      - opened

jobs:
  get_package_name:
    uses: martynov-alex/github_actions_examples/.github/workflows/get_package_name.yml@main

  create_pyrus_task:
    name: Create Pyrus task from pull request
    needs: get_package_name
    uses: martynov-alex/github_actions_examples/.github/workflows/create_pyrus_task_from_issue_or_pr.yml@main
    with:
      TYPE: Pull request
      PACKAGE_NAME: ${{ needs.get_package_name.outputs.package_name }}
      TITLE: ${{ github.event.pull_request.title }}
      BODY: ${{ github.event.pull_request.body }}
      LINK: ${{ github.event.pull_request.html_url }}
    secrets:
      LOGIN: ${{ secrets.PYRUS_BOT_LOGIN }}
      SECURITY_KEY: ${{ secrets.PYRUS_BOT_SECRET }}

  add_comment:
    name: Add comment
    needs: create_pyrus_task
    uses: martynov-alex/github_actions_examples/.github/workflows/add_comment_to_issue_or_pr.yml@main
    with:
      ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      COMMENT_TEXT: "[Link to Pyrus task](https://pyrus.com/t#id${{ needs.create_pyrus_task.outputs.task_id }})"
